spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false
    template-loader-path: classpath:/templates/
    suffix: .ftl
    content-type: text/html
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379